package com.outr.stripe.product

case class Product(id: String,
                   `object`: String,
                   active: Boolean,
                   attributes: List[String],
                   caption: Option[String],
                   created: Long,
                   deactivateOn: Option[List[String]],
                   description: Option[String],
                   images: List[String],
                   livemode: Boolean,
                   metadata: Map[String, String],
                   name: String,
                   packageDimensions: Option[PackageDimensions],
                   shippable: Option[Boolean],
                   statementDescriptor: Option[String],
                   `type`: String,
                   unitLabel: Option[String],
                   updated: Long,
                   url: Option[String])